### ISSUE TITLE
Undeclared dependency: vue-popper

### ISSUE THREAD

**Issue by wadetandy** [bloombergbna/fishtank-vue#42]
Vue-popper is currently declared as a dev dependency but when installing the newest version of fishtank-vue, I get an error that vue-popper is not installed, indicating it should be promoted to a full dependency.

**Comment by bakpa79** [comment]
@wadetandy Moved vue-popperjs to full dependancy and released [v1.1.0](https://www.npmjs.com/package/@fishtank/fishtank-vue/v/1.1.0) with the fix.
